version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Etc/GMT
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      artifact-actions:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
      github-actions-non-major:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: ci
