'use strict';

module.exports = {
  REQUEST: {CHECK_STATUS: 1, PLAY_SOUND: 2},
  RESULT: {
    OK: 0,
    CONFIG_MISSING: 1,
    CONFIG_INVALID: 2,
    BACKEND_UNAVAILABLE: 3,
    API_UNAUTHORIZED: 4,
    APPLE_AUTH_REQUIRED: 5,
    TARGET_NOT_FOUND: 6,
    SOUND_UNAVAILABLE: 7,
    RATE_LIMITED: 8,
    DEVICE_LOOKUP_FAILED: 9,
    OUTCOME_UNKNOWN: 10,
    APPLE_REQUEST_FAILED: 11,
    API_ERROR: 12
  }
};
